### ISSUE TITLE
Adding output of the script

### ISSUE THREAD

**Issue by Yokto13** [GordonHoklinder/hyppo#4]
It would be great if the user could see the output of the script. I would like to see how my script is doing during the process. Also it happened to me that the script was crashing and seeing only `exit status 2` isn't really helpful. 

It would make sense to debug any script crashing by running the script without hyppo. Yet, I tried this and it worked perfectly. Which is confusing and I will probably open another issue later when I have more time to figure out why is that happening. Anyway, having access to the output of the script would make all those things much more pleasant.

**Comment by GordonHoklinder** [comment]
Thanks for the issue.
The problem was not in your script but in hyppo as it passed all the arguments as one which resulted in error in your Python script.
Nevertheless printing the script's error output seems as a good idea as well. :)
